[tool.poetry]
name = "scalex"
version = "1.1.0"
description = "Online single-cell data integration through projecting heterogeneous datasets into a common cell-embedding space"
authors = ["Lei Xiong <jsxlei@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.7',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX :: Linux',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
]
homepage = 'https://github.com/jsxlei/scalex'
repository = 'https://github.com/jsxlei/scalex'
documentation = "https://scalex.readthedocs.io/en/latest/index.html"

[tool.poetry.scripts]
scalex = "scalex.__main__:main"

[tool.poetry.dependencies]
python = ">=3.9.3"
numpy = ">=1.17.2"
pandas = ">=0.25.1"
scipy = ">=1.3.1"
scikit-learn = ">=0.22.1"
torch = ">=1.0.0"
scanpy = ">=1.4.5"
tqdm = ">=4.28.1"
matplotlib = ">=3.0.3"
seaborn = ">=0.9.0"
leidenalg = ">=0.8.3"
episcanpy = "^0.4.0"
muon = "^0.1.3"

[tool.poetry.group.dev.dependencies]
sphinx-autodoc-typehints = "^1.22"
nbsphinx = "^0.9.1"
ipython = "^8.11.0"
black = "^23.1.0"
ruff = "^0.0.257"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.ruff]
target-version = "py310"
select = ["B", "C", "E", "F", "T", "W", "Q"]
# E127, E128 are hard to silence in certain nested formatting situations.
# E265, E266 talk about comment formatting which is too opinionated.
# E402 warns on imports coming after statements. There are important use cases
# like demandimport (https://fburl.com/demandimport) that require statements
# before imports.
# E501 is not flexible enough, we're using B950 instead.
# E722 is a duplicate of B001.
# P207 is a duplicate of B003.
# W503 talks about operator formatting which is too opinionated.
# E203 conflicts with Black
# ignore = ["E127", "E128", "E265", "E266", "E402", "E501", "E722", "P207", "W503", "E203", "T484"]
ignore = [
    "E501",
    "B008",
    "B905"
]
line-length = 80
exclude = [
    ".git",
    ".hg",
    "__pycache__",
    "_bin/*",
    "_build/*",
    "_ig_fbcode_wheel/*",
    "buck-out/*",
    "third-party-buck/*",
    "third-party2/*",
    "dist",
    ".venv",
    ".nox",
    ".mypy_cache",
    ".pytype",
    ".svn",
    "__pypackages__"
]

[tool.ruff.mccabe]
max-complexity = 50